
export const carMakes = [
  "AM General",
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "BMW",
  "Bentley",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Daewoo",
  "Datsun",
  "Dodge",
  "Eagle",
  "FIAT",
  "Ferrari",
  "Fisker",
  "Ford",
  "GMC",
  "Genesis",
  "Geo",
  "HUMMER",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "MINI",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mercury",
  "Mitsubishi",
  "Nissan",
  "Oldsmobile",
  "Panoz",
  "Plymouth",
  "Pontiac",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Saab",
  "Saturn",
  "Scion",
  "Smart",
  "Sterling",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
]

export const sortOptions = [
  { value: "", viewValue: "Best" },
  { value: "price:asc", viewValue: "Least Expensive" },
  { value: "price:desc", viewValue: "Most Expensive" },
  { value: "distance:asc", viewValue: "Nearest" },
  { value: "distance:desc", viewValue: "Farthest" },
  { value: "year:asc", viewValue: "Oldest" },
  { value: "year:desc", viewValue: "Newest" },
  { value: "mileage:asc", viewValue: "Least Miles" },
  { value: "mileage:desc", viewValue: "Most Miles" },
  { value: "created_at:asc", viewValue: "Newest Listings" },
  { value: "created_at:desc", viewValue: "Oldest Listings" },
];


export interface SearchParams {
  year_min: string,
  make: string,
  model: string,
  trim: string,
  city: string,
  state: string,
  latitude: string,
  longitude: string,
  location: string,
  radius: string,
  transmission: string,
  features: string,
  exterior_color: string,
  interior_color: string,
  milage: string,
  driveline: string,
  condition: string,
  exclude_regional: string,
  exclude_no_price: string,
  sort_filter: string,
  price_max: string,
  price_min: string,
}
