
export interface SearchParams {
  year_min: string,
  make: string,
  model: string,
  trim: string,
  city: string,
  state: string,
  latitude: string,
  longitude: string,
  location: string,
  radius: string,
  transmission: string,
  features: string,
  exterior_color: string,
  interior_color: string,
  milage: string,
  driveline: string,
  condition: string,
  exclude_regional: string,
  exclude_no_price: string,
  sort_filter: string,
  price_max: string,
  price_min: string,
}
